# Grunt aliases
---
# Build everything
build:
  - 'build:assets'
# Build assets
'build:assets':
  - 'clean'
  - 'sass'
  - 'concat'
  - 'cssmin'
  - 'copy:dist'
# Deploy
deploy:
  - 'build'
# Dist
dist:
  - 'build'
# Default
default:
  - 'build'
  - 'watch'
